name: immersya_pathfinder
description: "A virtual world where everything is possible."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2

  # ----- NOUVELLE STACK CARTOGRAPHIQUE -----
  flutter_map: ^6.1.0  # La librairie principale pour la carte
  latlong2: ^0.9.0    # Requis par flutter_map pour la gestion des coordonnées

  # Accès aux capteurs et fonctionnalités natives
  camera: ^0.10.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # Réseau & Données
  http: ^1.2.0
  
  # Gestion de l'état
  provider: ^6.1.2

  # Utilitaires
  path_provider: ^2.1.3

  # ... autres dépendances
  intl: ^0.18.1 # ou la version la plus récente
  model_viewer_plus: ^1.7.0 # ou la version la plus récente
  shared_preferences: ^2.2.3 # ou la version la plus récente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cesium/