name: immersya_mobile_app
description: "A virtual world where everything is possible."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0

  # UI & Navigation
  cupertino_icons: ^1.0.2

  # ----- NOUVELLE STACK CARTOGRAPHIQUE -----
  flutter_map: ^6.1.0  # La librairie principale pour la carte
  latlong2: ^0.9.0    # Requis par flutter_map pour la gestion des coordonnées

  # Accès aux capteurs et fonctionnalités natives
  camera: ^0.10.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # Réseau & Données
  http: ^1.2.0
  
  # Gestion de l'état
  provider: ^6.1.2

  # Utilitaires
  path_provider: ^2.1.3

  # ... autres dépendances
  intl: ^0.18.1 # ou la version la plus récente
  model_viewer_plus: ^1.7.0 # ou la version la plus récente
  shared_preferences: ^2.2.3 # ou la version la plus récente
  flutter_launcher_icons: ^0.13.1 # ou la version la plus récente
  polygon: ^0.1.0
  geocoding: ^2.1.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  # --- Configuration pour Android ---
  android: "launcher_icon" # Nom de l'icône pour Android (garder cette valeur)
  image_path: "assets/icon/icon.png" # Chemin vers VOTRE image
  min_sdk_android: 21 # SDK minimum pour les icônes adaptatives

  # --- Configuration pour iOS ---
  ios: true # Activer la génération pour iOS
  image_path_ios: "assets/icon/icon.png" # Vous pouvez spécifier une icône différente si besoin
  remove_alpha_ios: true # iOS n'aime pas la transparence alpha sur l'icône principale